title: Sticky Construction, Inc.
email: hello@hisaac.net
description: The homepage of Sticky Construction, Inc., a commercial caulking company located in Thompson, ND.
baseurl: ""
url: "https://sticky-construction.com"

# Build settings
livereload: true
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
